Lesson4
s1tt/Gb-Java-02 pull request #4
Opened 2022-04-04 02:46 UTC by s1tt

2022-04-04 05:00 UTC, efserg requested changes
Ну вы хотя бы имена переменных-то поменяйте :(

2022-04-04 05:00 UTC, efserg commented on src/main/java/com/geekbrains/chat/ChatController.java
> +        if (playerNumber.isEmpty()) {
playerNumber?

2022-04-04 15:10 UTC, s1tt commented on src/main/java/com/geekbrains/chat/ChatController.java
> +        if (playerNumber.isEmpty()) {
Упс, пока разбирался почему выскакивает и как исправить "master and lesson4 are entirely different commit histories" такой очевидный косяк пропустил :(
Поправил

2022-04-05 04:58 UTC, efserg approved these changes

2022-06-06 15:09 UTC, merged